import { mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const MODEL_FILE = join(process.cwd(), ".cyrene", "model.yaml");

const parseScalar = (value: string) =>
  value.replace(/^["']/, "").replace(/["']$/, "").trim();

export const loadModelYaml = async (): Promise<{
  models: string[];
  defaultModel?: string;
}> => {
  const content = await readFile(MODEL_FILE, "utf8");
  const models: string[] = [];
  let defaultModel: string | undefined;

  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    if (line.startsWith("default_model:")) {
      defaultModel = parseScalar(line.slice("default_model:".length));
      continue;
    }
    if (line.startsWith("-")) {
      const model = parseScalar(line.slice(1));
      if (model) {
        models.push(model);
      }
    }
  }

  if (models.length === 0) {
    throw new Error("model.yaml has no models");
  }

  return {
    models,
    defaultModel,
  };
};

export const saveModelYaml = async (
  models: string[],
  defaultModel: string
): Promise<void> => {
  const unique = Array.from(new Set(models.map(model => model.trim()))).filter(
    Boolean
  );
  if (unique.length === 0) {
    throw new Error("Cannot save empty model list");
  }

  const normalizedDefault = unique.includes(defaultModel)
    ? defaultModel
    : unique[0];

  const lines = [
    "# Auto-generated by /model refresh",
    `default_model: ${normalizedDefault}`,
    "models:",
    ...unique.map(model => `  - ${model}`),
    "",
  ];

  await mkdir(join(process.cwd(), ".cyrene"), { recursive: true });
  await writeFile(MODEL_FILE, lines.join("\n"), "utf8");
};

